version: "3.9"

services:
  # === Keycloak (auth) ===
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8089:8080" # admin console & OIDC endpoints (host:8089)
    networks:
      - backend

  # === Mongo for user-service ===
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017" # exposed for dev/test; can remove in prod
    networks:
      - backend
    volumes:
      - mongodb_data:/data/

      # === Mongo for user-service ===
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379" # exposed for dev/test; can remove in prod
    networks:
      - backend
    volumes:
      - redis_data:/data/

  # === Eureka discovery server ===
  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761" # dev only; disable in prod
    networks:
      - backend

  # === user-service (Mongo + Eureka client) ===
  user-service:
    build: ./user-service
    depends_on:
      - mongodb
      - discovery-server
    environment:
      MONGO_URI: mongodb://mongodb:27017
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASS: admin
    networks:
      - backend

  # === API Gateway (public entry) ===
  api-gateway:
    build: ./api-gateway
    depends_on:
      - discovery-server
      - user-service
      - keycloak
      - redis
    ports:
      - "8080:8080" # only public-facing service
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
    networks:
      - backend

networks:
  backend:

volumes:
  mongodb_data:
  redis_data:
